steps:
#  # Checkout your source code
#  - name: "gcr.io/cloud-builders/git"
#    args: ["clone", "https://github.com/athuls121/devops-secret-keeper.git", "."]

  # Authenticate with Google Cloud
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ls -l
        gcloud auth activate-service-account --key-file=/terraform/credentials.json

  # Change directory to the Terraform directory
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd terraform  

  # Initialize Terraform
  - name: "hashicorp/terraform:latest"
    args:
      - "init"
      - "-upgrade"

  # Plan Terraform changes
  - name: "hashicorp/terraform:latest"
    args:
      - "plan"

  # Apply Terraform changes
  - name: "hashicorp/terraform:latest"
    args:
      - "apply"
      - "-auto-approve"



    # build the container name
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]

    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
    
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=gke.yaml
    - --image=gcr.io/$PROJECT_ID/gcpdevops
    - --location=us-central1
    - --cluster=gcp-devops-project-clust
    - --namespace=gcp-devops-prod
