steps:
# List contents of the directory to verify Terraform files
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd /home/athuls121/devops-secret-keeper
        ls -la

  # Initialize Terraform
  - name: "hashicorp/terraform:latest"
    args:
      - "init"
    dir: "/home/athuls121/devops-secret-keeper"  # Path to the Terraform directory in Cloud Shell

  # Plan Terraform changes
  - name: "hashicorp/terraform:latest"
    args:
      - "plan"
    dir: "/home/athuls121/devops-secret-keeper"  # Path to the Terraform directory in Cloud Shell

  # Apply Terraform changes
  - name: "hashicorp/terraform:latest"
    args:
      - "apply"
      - "-auto-approve"
    dir: "/home/athuls121/devops-secret-keeper"  # Path to the Terraform directory in Cloud Shell


    # build the container name
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]

    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
    
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=gke.yaml
    - --image=gcr.io/$PROJECT_ID/gcpdevops
    - --location=us-central1
    - --cluster=gcp-devops-project-clust
    - --namespace=gcp-devops-prod
