steps:
  # Authenticate with Google Cloud
  # Change directory to the Terraform directory
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ls -l
        gcloud auth activate-service-account --key-file=terraform/credentials.json
        cd terraform

  # Initialize, Plan and Apply Terraform
  - name: "hashicorp/terraform:latest"
    dir: "terraform"
    args:
      - "init"
      - "-upgrade"

  - name: "hashicorp/terraform:latest"
    dir: "terraform"
    entrypoint: "/bin/sh"
    args:
      #- "plan"
      - "-c"
      - |
        terraform plan -detailed-exitcode || TF_EXITCODE=$?
        if [[ $? -eq 0 || $? -eq 2 ]]; then
          echo "Terraform plan successful or with changes"
        elif [[ $? -eq 1 ]]; then
          echo "Terraform plan failed"
          # Handle failure if needed
          exit 1
        elif [[ $? -eq 3 ]]; then
          echo "No changes to apply, Terraform succeeded"
        else
          echo "Terraform exited with an unexpected code: $TF_EXITCODE"
          exit 1
        fi

  - name: "hashicorp/terraform:latest"
    dir: "terraform"
    args:
      - "apply"
      - "-auto-approve"



    # build the container name
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]

    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
    
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=gke.yaml
    - --image=gcr.io/$PROJECT_ID/gcpdevops
    - --location=us-central1
    - --cluster=gcp-devops-project-clust
    - --namespace=gcp-devops-prod



    # Execute the Python test file
  - name: "python:3.9"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        python test_secret_keeper.py


