steps:

    # Execute the Python test file
  - name: "python:3.12"
    entrypoint: "bash"
    args:
      - "-c"
      - |
         python3 -m venv myenv  # Create a virtual environment
         source myenv/bin/activate  # Activate the virtual environment
         pip install --upgrade pip
         pip install -r requirements.txt
         python test_secret_keeper.py

    # build the container name
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]

    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
    
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=gke.yaml
    - --image=gcr.io/$PROJECT_ID/gcpdevops
    - --location=us-central1
    - --cluster=gcp-devops-project-clust
    - --namespace=gcp-devops-prod

