steps:
  # Authenticate with Google Cloud
  # Change directory to the Terraform directory
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ls -l
        gcloud auth activate-service-account --key-file=terraform/credentials.json
        cd terraform

#  # Initialize, Plan and Apply Terraform
#  - name: "hashicorp/terraform:latest"
#    dir: "terraform"
#    args:
#      - "init"
#      - "-upgrade"
#
#  - name: "hashicorp/terraform:latest"
#    dir: "terraform"
#    args:
#      - "plan"
#
#  - name: "hashicorp/terraform:latest"
#    dir: "terraform"
#    args:
#      - "apply"
#      - "-auto-approve"



    # build the container name
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]

    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
    
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=gke.yaml
    - --image=gcr.io/$PROJECT_ID/gcpdevops
    - --location=us-central1
    - --cluster=gcp-devops-project-clust
    - --namespace=gcp-devops-prod



    # Execute the Python test file
  - name: "python:3.9"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        EXTERNAL_IP=$(gcloud compute instances describe gcp-devops-gke-service --zone=ZONE --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
        echo "EXTERNAL_IP=${EXTERNAL_IP}" >> ${_DEFAULT_OUTPUT_FILE}
    substitutions:
      _DEFAULT_OUTPUT_FILE: "substitutions_file.yaml"
      INSTANCE_NAME: "YOUR_INSTANCE_NAME"
      ZONE: "YOUR_INSTANCE_ZONE"


  # Run the Python test file
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export EXTERNAL_LOAD_BALANCER_IP=$(gcloud compute instances describe gcp-devops-gke-service --format='get(networkInterfaces[0].accessConfigs[0].natIP)')

        pip install pywebio pytest flask numpy requests os
        python test_secret_keeper.py
    substitutions:
      _EXTERNAL_LOAD_BALANCER_IP: "EXTERNAL_LOAD_BALANCER_IP"


#  # Destroy Terraform
#  - name: "hashicorp/terraform:latest"
#    dir: "terraform"
#    args:
#      - "destroy"
#      - "-auto-approve"

