apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/cellular-way-399223/gcpdevops:latest
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        - name: REDIS_HOST
          value: "10.251.173.211"  # Replace with your Redis host
        - name: REDIS_PORT
          value: "6379"
        readinessProbe:
          httpGet:
            path: /admin/health
            scheme: HTTP
            port: 8083
          initialDelaySeconds: 150   # Adjust as needed
          periodSeconds: 5        # Adjust as needed
          timeoutSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health/local
            scheme: HTTP
            port: 8083
          initialDelaySeconds: 120  # Adjust as needed
          periodSeconds: 5        # Adjust as needed
          timeoutSeconds: 5
          failureThreshold: 10


---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: gcp-devops-prod
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
  selector:
    app: gcp
  type: LoadBalancer
